Feat subscribe sqs gmc doctors tis doctors jay test
Health-Education-England/tis-revalidation-integration pull request #204
Opened 2021-04-22 09:23 UTC by jayanta2018

This is a PR which was raised earlier as draft PR and we worked on it accordingly.

2021-04-22 09:34 UTC, Judge40 requested changes

2021-04-22 09:34 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
Could this be simplified with a mapper?

2021-04-22 09:34 UTC, Judge40 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
> +  DoctorUpsertElasticSearchService doctorUpsertElasticSearchService;
This can be private

2021-04-22 09:34 UTC, Judge40 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +  private List<MasterDoctorView> recordsAlreadyInEs;
This is only used in one place and doesn't warrant being a field.

2021-04-22 09:34 UTC, Judge40 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +    masterDoctorView.setId(recordsAlreadyInEs.get(0).getId());
The only item in `recordAlreadyInEs` is `masterDoctorView`, so this both sets to and gets from the same object and is redundant.

2021-04-22 09:57 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
Good Question @Judge40 . I initially thought  I could use mapper but I was confused here. Not all the fileds will be changed/updated in the ES document. Some of them will remain same as in masterDoctorDocumentToSave. I.e. connectionStatus, designatedBody, etc.
What is your suggestions on this?

2021-04-22 10:12 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
Just found something. I will try with @jsonignore.  I will let you know, how it goes after testing in my local

2021-04-22 10:21 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
Mapstruct's `@Mapping` annotation has an ignore flag, that can be used for this.
e.g. `@Mapping(target = "whatever-the-target-is", ignore = true)`

2021-04-22 11:49 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
@Judge40 

Struggling to implement this. My source and target object are the same, which is MasterDoctorView.class.

I have implemented the following  way:

existingRecords.forEach(currentDoctorView -> {
      
      masterDoctorElasticSearchRepository
          .save(mapper.convertValue(currentDoctorView, MasterDoctorView.class));
    });

Don't know if I need a separate mapper interface. As I don't have it I cannot implement "ignore" some fields.
Please advice.

2021-04-22 11:50 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
"mapper" here is ObjectMapper object

2021-04-22 11:58 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
Your technique won't work because you need to combine both objects, `ObjectMapper` is just a straight forward type to type conversion so does not have a way to do that.

As mentioned above, you should use mapstruct for this. You'll find this section of the docs useful:
https://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances

A search for `@MappingTarget` in our Github org will show how we've used it in the past (including some in combination with `@Mapping(... ignore = true)`)

2021-04-22 14:14 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +      dataToSave.setMembershipEndDate(currentDoctorView.getMembershipEndDate());
@Judge40 
@MappingTarget was the solution. Many thanks

2021-04-22 14:14 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
> +  DoctorUpsertElasticSearchService doctorUpsertElasticSearchService;
Done

2021-04-22 14:15 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +  private List<MasterDoctorView> recordsAlreadyInEs;
It is taken care of

2021-04-22 14:15 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +    masterDoctorView.setId(recordsAlreadyInEs.get(0).getId());
Good spot. I have reduced the redundancy.

2021-04-22 14:20 UTC, Judge40 requested changes

2021-04-22 14:20 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +  public void addMasterDoctorViews(MasterDoctorView dataToSave) {
If this has only been made public to allow direct testing then the test should be rewritten to perform that verification by calling `populateMasterIndex`. Alternatively, just delete this method and perform the save in `populateMasterIndex` since its a single line method used in a single place.

2021-04-22 14:20 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
> +  MasterDoctorView fromTo(MasterDoctorView masterDoctorView,
`source` and `target` would be better names, also consider renaming the method to be clearer e.g. `update`

2021-04-22 14:20 UTC, Judge40 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
>      setField(gmcDoctorMessageListener, "sqsEndPoint", "sqsEndPoint");
I couldn't see anywhere that the listener actually uses this field, do removing it from the test cause a failure?
Maybe remove it from the listener itself?

2021-04-22 14:33 UTC, Judge40 requested changes

2021-04-22 14:33 UTC, Judge40 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +    verify(masterDoctorElasticSearchRepository).save(masterDoctorView);
We verify that an object matching our input object is saved, but we don't have anything that tests whether we update/merge the records because the result of `masterDoctorElasticSearchRepository.search()` is mocked to an empty list (i.e. no pre-existing record).

2021-04-22 15:39 UTC, Judge40 requested changes

2021-04-22 15:39 UTC, Judge40 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
> + * Copyright 2020 Crown Copyright (Health Education England)
The copyright had the wrong year on it.

2021-04-22 15:42 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
> + * Copyright 2020 Crown Copyright (Health Education England)
Sorry for not noticing this

2021-04-22 15:46 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +    verify(masterDoctorElasticSearchRepository).save(masterDoctorView);
I am looking into this. 3 private methods are called inside the "populateMasterIndex". Not finding a better to verify the if else flow based on the index search. Mockito does not support the private method test, but PowerMockito does.
Any clue how can I test the populateMasterIndex() method with the if else flow?

2021-04-22 18:32 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchService.java
> +  public void addMasterDoctorViews(MasterDoctorView dataToSave) {
I have refactored the code and wrote the test from a new perspective. Many thanks for the suggestion.

2021-04-22 18:32 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/router/mapper/MasterDoctorViewMapper.java
> +  MasterDoctorView fromTo(MasterDoctorView masterDoctorView,
applied the ideas

2021-04-22 18:33 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListenerTest.java
>      setField(gmcDoctorMessageListener, "sqsEndPoint", "sqsEndPoint");
Yeah, good spot
I have removed it

2021-04-22 18:33 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +    verify(masterDoctorElasticSearchRepository).save(masterDoctorView);
Found a new way of writing the tests, utilising the mapper

2021-04-22 19:22 UTC, Judge40 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +    verify(masterDoctorElasticSearchRepository).save(masterDoctorView);
Didn't see your earlier message as I'd already finished, I'm not clear on the problem you've had to try solve here. Let's have a call in the morning and work through it.

2021-04-23 08:25 UTC, jayanta2018 commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/DoctorUpsertElasticSearchServiceTest.java
> +    verify(masterDoctorElasticSearchRepository).save(masterDoctorView);
Sure @Judge40 . Let's have a call. 
Many thanks for taking time to check my PR

2021-04-23 16:04 UTC, Judge40 approved these changes

2021-04-23 16:07 UTC, merged