feat: added revalidation fields to master index
Health-Education-England/tis-revalidation-integration pull request #308
Opened 2022-03-09 13:52 UTC by jayanta2018

TIS21-2669

The additional fields which are needed to make the revalidation summary page for elastic search index is added in this PR. The fields are being received from the sqs queue.

2022-03-09 13:59 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
> +  public void getMessage(RevalidationSummaryDto doctor) {
probably change the parameter name from doctor to something clearer (e.g. revalidationSummaryDto?)

2022-03-09 15:16 UTC, DorisWongNHS commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/entity/RevalidationSummaryDto.java
> + * Copyright 2021 Crown Copyright (Health Education England)
This may need to changed as 2022

2022-03-09 15:40 UTC, DorisWongNHS commented
The original queue used to pass "getMaster" signal to Connection is going to be refactored. The routing key may need to be updated here in the Integration service, but the name is not confirmed yet. Please follow the conversation here if you are interested.
https://github.com/Health-Education-England/TIS-RabbitMQ/pull/74

2022-03-10 13:08 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
> +    final var doctorsForDB = message.getPayload().getDoctor();
wondering if this should go in the "else" statement, if syncEnd is true then all of these fields will be null

2022-03-10 15:52 UTC, DorisWongNHS requested changes
The update of the routing key may have missed. Sorry.

2022-03-10 16:21 UTC, DorisWongNHS commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/view/MasterDoctorView.java
> +  private LocalDate curriculumEndDate;
Extra annotation may need in front of date
`@Nullable
  @Field(type = FieldType.Date, format = DateFormat.custom, pattern = "uuuu-MM-dd")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")`

2022-03-10 16:22 UTC, DorisWongNHS commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/view/MasterDoctorView.java
> +  private LocalDate lastUpdatedDate;
Extra annotation may need in front of date
`@Nullable
  @Field(type = FieldType.Date, format = DateFormat.custom, pattern = "uuuu-MM-dd")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")`

2022-03-11 10:36 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
> +    final var doctorsForDB = message.getPayload().getDoctor();
@CaiWillis Thanks. Good spot

2022-03-11 12:30 UTC, DorisWongNHS requested changes

2022-03-11 12:30 UTC, DorisWongNHS commented on src/main/resources/application.yml
> +    reval.indexrebuildgetmastercommand.requested: ${REVAL_RABBIT_GETMASTER_ROUTING_KEY:reval.connection.getmaster}
The part at the end after `:` is the place where we put the value. Where the front part is like a param name.
It could be `reval.routingKey.indexrebuildgetmastercommand.requested: ${REVAL_RABBIT_GETMASTER_ROUTING_KEY:reval.indexrebuildgetmastercommand.requested}`

The file `GmcDoctorMessageListener.java` used this param in the `@Value` annotation, where it also needs your update.

2022-03-11 12:33 UTC, jayanta2018 commented on src/main/resources/application.yml
> +    reval.indexrebuildgetmastercommand.requested: ${REVAL_RABBIT_GETMASTER_ROUTING_KEY:reval.connection.getmaster}
Thanks @DorisWongNHS for your keen observation

2022-03-11 14:27 UTC, DorisWongNHS approved these changes

2022-03-11 14:27 UTC, merged