feat: Listen for CDC changed and update Master Doctor Index
Health-Education-England/tis-revalidation-integration pull request #318
Opened 2022-04-11 14:17 UTC by CaiWillis

TIS21-2748: Add endpoints/listeners Integration service to update master index

2022-04-13 08:27 UTC, CaiWillis commented
![integration_cdc_classes](https://user-images.githubusercontent.com/78361963/163133745-e625c7ec-7932-4b18-9f7e-d30d64f1e45d.png)

2022-04-13 09:45 UTC, JosephKelly reviewed
I would have liked to 'check my working' more but I think my comments are right.

I'd forget if it were me so I'm just acknowledging your previous message about copyrights.

2022-04-13 09:45 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/handler/CdcMessageHandler.java
> +public class CdcMessageHandler<T extends ChangeStreamDocument> implements MessageHandler<T> {
Looking at the use of this I wasn't sure it should be a `@Component` and probably an `abstract class`.
:point_up: that seems consistent with your image describing it as a "Base Class".

2022-04-13 09:45 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcSqsMessageListener.java
> +  @SqsListener(value = "${}")
I think `value = ` is redundant.  `@SqsListener("${}")` should do.
I'm not familiar with these annotations so don't know if there is a property name that you'll be adding.

2022-04-13 09:45 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcSqsMessageListener.java
> +  @SqsListener(value = "${}")
`@SqsListener("${}")` should do.

2022-04-13 10:05 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcSqsMessageListener.java
> +  @SqsListener(value = "${}")
Whoops! That's definitely supposed to have a value!

2022-04-13 10:09 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/handler/CdcMessageHandler.java
> +public class CdcMessageHandler<T extends ChangeStreamDocument> implements MessageHandler<T> {
So this class is mostly to reduce code re-use - handle message is always going to have the same logic so don't think it needs to be abstract, and the subclasses are mostly used to inject the correct type and CdcService implementation - what do you think?

2022-04-13 10:21 UTC, CaiWillis commented on build.gradle
> +  implementation 'org.mongodb:mongodb-driver-sync:4.5.1'
Unfortunately this relies quite heavily on ChangeStreamDocument for which I think the library is mongodb-driver-sync

2022-04-13 10:51 UTC, JosephKelly commented on build.gradle
> +  implementation 'org.mongodb:mongodb-driver-sync:4.5.1'
ChangeStreamDocument looks like it's in `org.mongodb:mongodb-driver-core:4.5.1`.  Not sure what/if difference that would make

2022-04-13 14:44 UTC, DorisWongNHS commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcSqsMessageListener.java
> +  @SqsListener(value = "${}")
Just FYR, the queues for Preprod are created with Terrafrom, and here is the param name for the queue `/tis/revalidation/documentdb-cdc/preprod/queue-url/recommendation` (if no objection about the queue name). You may update application.yml and task-definition.json for this if you want.
Related PR: https://github.com/Health-Education-England/TIS-OPS/pull/434/files

2022-04-14 09:57 UTC, JosephKelly reviewed
It looks like whitespace formatting needs to be applied to the MessageHandler classes (& maybe elsewhere in changed files.

I unresolved 1 thread about the dependency but it's nearing that point where I feel like I should have invested more effort in making a recommendation over and above pointing at things that might need to be looked at.

2022-04-14 09:57 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/handler/CdcMessageHandler.java
> +public class CdcMessageHandler<T extends ChangeStreamDocument, U> implements MessageHandler<T> {
This is equivalent to `public class CdcMessageHandler<T> implements MessageHandler<ChangeStreamDocument<T>>`

You'd need to change the parameter type of handleMessage() from `T` to `ChangeStreamDocument<T>` but I thought I'd see if you think it's simpler / more readable that way.

2022-04-14 09:59 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/handler/CdcMessageHandler.java
> +public class CdcMessageHandler<T extends ChangeStreamDocument> implements MessageHandler<T> {
I am struggling to see where it actually gets used.  The subclasses get pulled in but there doesn't seem to be a used of CdcMessageHandler that is used.

2022-04-14 10:11 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/handler/CdcMessageHandler.java
> +public class CdcMessageHandler<T extends ChangeStreamDocument, U> implements MessageHandler<T> {
Thanks! that was bothering me

2022-04-20 15:40 UTC, DorisWongNHS approved these changes

2022-04-20 15:46 UTC, JosephKelly submitted a review, later dismissed
Sorry I still haven't given as thorough a review of the tests as I would have liked but much happier with the code :-)

Haven't merged as I don't know if parameters are in place

2022-04-20 15:57 UTC, DorisWongNHS requested changes

2022-04-20 15:57 UTC, DorisWongNHS commented on .aws/task-definition-prod.json
> +          "valueFrom": "tis/revalidation/documentdb-cdc/prod/queue-url/doctorsfordb"
Missing `/` at the front of the param name

2022-04-20 15:57 UTC, DorisWongNHS commented on .aws/task-definition.json
> +          "valueFrom": "tis/revalidation/documentdb-cdc/preprod/queue-url/doctorsfordb"
Missing `/` at the front of the param name

2022-04-20 16:01 UTC, DorisWongNHS commented
@JosephKelly good call. While I double check the param name, I found a type of missing `/`. I had a check from the param store, both queues for Preprod are in place on AWS, and I am applied the queues to Prod by Terraform with this PR: https://github.com/Health-Education-England/TIS-OPS/pull/438

2022-04-21 08:11 UTC, JosephKelly approved these changes

2022-04-21 09:24 UTC, DorisWongNHS approved these changes

2022-04-21 09:24 UTC, jayanta2018 approved these changes

2022-04-21 09:25 UTC, merged