refactor: handle trainee updates in integration service
Health-Education-England/tis-revalidation-integration pull request #332
Opened 2022-05-18 10:07 UTC by CaiWillis

TIS21-2873:[Filter Recommendations with ES] - Event Handling Job For Data Changes (TIS)

2022-05-25 11:32 UTC, JosephKelly approved these changes

2022-05-25 11:49 UTC, JosephKelly requested changes
Also pushed a branch with a tiny tweak to improve code coverage.

2022-05-25 11:49 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java
> +  void shouldAddNewFields() {
Looks like it's missing a `@Test`.

2022-05-25 11:49 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java
> +    verify(repository).save(any());
I can't see assertions that line up with the method name.  You could use a `@Captor MasterDoctorView masterDoctorView;` to check the fields are added/removed as expected.

2022-06-13 15:05 UTC, JosephKelly reviewed
Sorry I left a partial review to get stale.  I've left a little comment and had been working on a slight refactoring to the `CdcTraineeUpdateService.upsertEntity()` method... it's probably different enough to raise after this has been fully reviewed/merged.

I've left a comment by part of the implementation that seems to be a bit more "unspecified" behavior.  Let me know if that needs clarifying

2022-06-13 15:05 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +    } else {
It's not obvious that we should / shouldn't publish the "updatedView" even if there is no GMC information.  I think the tests should clearly `verifyNoInteractions()` or verify the expected CdcMessagePublisher invocation(s)

2022-06-13 16:32 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcTraineeUpdateServiceTest.java
> +    verify(repository).save(any());
I could be tired but I have inferred a reliance on GMC number being null when we have never received a GMC record but this isn't verified by an assertion.

2022-06-15 12:13 UTC, JosephKelly approved these changes

2022-06-16 11:15 UTC, hihilary approved these changes

2022-06-16 11:23 UTC, merged