Feat/reommendation resync by reindex
Health-Education-England/tis-revalidation-integration pull request #375
Opened 2022-12-09 01:54 UTC by hihilary

2022-12-09 11:03 UTC, hihilary commented
SonarCloud complained there's bug that the "ElasticsearchRestClient" needs to be closed in the config file, shown as below:
![image](https://user-images.githubusercontent.com/33690649/206687539-28b3992e-bb2f-433c-bcc5-ee4cdd6ce7d1.png)

But this is not a bug, as the lifecycle of the Bean is usually managed by the Spring IOC container. Someone also raised this to Sonar team: https://community.sonarsource.com/t/fp-in-s2095-use-try-with-resources-or-close-this-elasticsearchrestclient-in-a-finally-clause/16295.

And the documentation of the spring-data-elasticsearch is here: https://docs.spring.io/spring-data/elasticsearch/docs/4.2.5/reference/html/#elasticsearch.clients.rest

2022-12-09 11:38 UTC, hihilary commented on src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> +mock-maker-inline
Add this config to let Mockito allow to mock final classes, eg. `IndicesClient` in HelperTest.

2022-12-09 15:46 UTC, JosephKelly requested changes
I haven't reviewed whether the resync makes sense to me.  Specifically, I was trying to cover whether this works when "masterdoctorindex" is an alias.

~I'm not certain about the validity/correctness of the copyright year in new files.  I'd like to find out.~  :RESOLVED:

I noticed all the `protected` access modifiers on methods in `ElasticsearchIndexService.java`.  Are you purposely making this class extendable?  If you want to test the methods in a unit test, the "defualt" access would be sufficient.

2022-12-09 15:46 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexService.java
> +          newTargetIndexName, e);
Again, do we miss the stacktrace here?

2022-12-09 15:46 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexService.java
> +          backupAlias, e);
Again, do we miss the stacktrace?

2022-12-09 16:02 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/helper/ElasticsearchIndexHelper.java
> +      .build();
The timeouts can be configured in ElasticSearchConfig as well as in every individual API request to ES. The default timeouts are: connect time out 1s, socket timeout 30s. 
When I tested all the APIs on my local during the resync process, I found only Reindex API usually got a socket timeout, and for others, the responses are super quick.

Btw, Elasticsearch Java REST client provides both synchronous and asynchronous ways to fetch data from ES, but for asynchronous execution, we need to add lots of listeners or anonymous inner classes for every step. So I decided to do synchronous execution.
The documentation of reindex API can be found here: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.4/java-rest-high-document-reindex.html

2022-12-09 16:11 UTC, hihilary commented
> I haven't reviewed whether the resync makes sense to me. Specifically, I was trying to cover whether this works when "masterdoctorindex" is an alias.
> 
> ~I'm not certain about the validity/correctness of the copyright year in new files. I'd like to find out.~ :RESOLVED:
> 
> I noticed all the `protected` access modifiers on methods in `ElasticsearchIndexService.java`. Are you purposely making this class extendable? If you want to test the methods in a unit test, the "defualt" access would be sufficient.

Good spot. I haven't tested this process when "masterdoctorindex" yet, but it's worthing having a check.
However, the "masterdoctorindex" here can be the real index name as "materdoctorindex_yyyyMMddHHmmss".

For the `protected` access, I was thinking we might want to extend it for connection or masterdoctor indices in the future. But probably not.

2022-12-09 16:17 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
> +          .underNotice(doctorsForDB.getUnderNotice()).existsInGmc(doctorsForDB.getExistsInGmc())
These changes are from Cai's first commit. I think they've been an unintentional change, I will remove them.

2022-12-13 09:48 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/helper/ElasticsearchIndexHelper.java
> +      log.error(e.getMessage());
Thanks, have made the object a singleton bean.

2022-12-13 09:55 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/helper/ElasticsearchIndexHelper.java
> +      throw e;
Have altered as suggested and seems no code smell is identified.
IMHO, rethrowing the same exception to the caller is reasonable, because it allows the caller reacts to the exception and there's no need to alter it to some exception else.

2022-12-13 09:55 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/listener/GmcDoctorMessageListener.java
> +          .underNotice(doctorsForDB.getUnderNotice()).existsInGmc(doctorsForDB.getExistsInGmc())
Fixed.

2022-12-13 09:55 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexService.java
> +      ElasticsearchIndexHelper elasticsearchIndexHelper) {
Fixed.

2022-12-13 10:02 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexService.java
> +    if (!aliasExists) {
fixed

2022-12-13 10:02 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexService.java
> +          newTargetIndexName, e);
Thanks, fixed.

2022-12-13 10:02 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexService.java
> +          backupAlias, e);
fixed.

2023-01-06 12:34 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/helper/ElasticsearchIndexHelper.java
> +      .build();
Crossed wires / I wasn't clear enough... I was wondering if the `RequestConfig` should be a Spring bean... at the moment it is only used in this class.  The default scope for beans is singleton so `ElasticsearchIndexHelper` should already be a singleton.

2023-01-06 14:55 UTC, JosephKelly requested changes
There are some things that I'd like you to consider changing in the test classes.  I'm around if you want to discuss/run through.

Sorry about the delay getting onto it. Let me know if you want me to make some changes as a penance.

2023-01-06 14:55 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    AliasMetadata aliasMetadata1 = mock(AliasMetadata.class);
As above, unnecessary if defined with other `@Mock`s.

2023-01-06 14:55 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    verify(elasticsearchIndexHelperMock, times(0)).addAlias(anyString(), anyString());
Again, `Mockito.never()`.

2023-01-06 14:55 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    MappingMetadata mappingMock = mock(MappingMetadata.class);
As above, unnecessary if defined with other `@Mock`s.

2023-01-06 14:55 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +  }
This looks like a good candidate for `@ParameterizedTest`, combined with the one above.

2023-01-06 14:55 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    MappingMetadata mappingMock = mock(MappingMetadata.class);
As above, unnecessary if defined with other `@Mock`s.

2023-01-06 15:15 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/config/EsRestClientConfig.java
> +  private String esPort;
I was just trying to run the app from the branch but couldn't see where these were defined.  There is a `spring.elasticsearch.rest.uris` in `application.yml` config file.  Have I missed something?

2023-01-06 15:26 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/config/EsRestClientConfig.java
> +  private String esPort;
No, my bad. I configured something on my local but haven't included this in my PR. 🙈 
Please bear me to fix this and will let you know later.

2023-01-06 21:57 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +  void shouldNotDeleteBackupIndicesWhenOneHasCreationDateOthersNot() throws Exception {
Thanks for spotting this. 
I've fixed the logic back to ignore the indices whose `creation_date` is empty.

2023-01-06 22:13 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/sync/helper/ElasticsearchIndexHelper.java
> +      log.error(e.getMessage());
The `RequestConfig` can be a Spring bean in the `EsRestClientConfig` file, but that's something like overwriting the default timeouts for every request.
I don't think we need so long timeouts for queries, so just set a single `RequestConfig` for reindexing only.

2023-01-06 23:17 UTC, hihilary commented on src/main/resources/application.yml
> +      uris: ${ES_URLS:localhost:9200}
The prefix `http://` does not exist in the ES url of Stage & Prod in parameter store.
And the ClientConfiguration does not want it.

2023-01-09 09:29 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    verify(elasticsearchIndexHelperMock, times(0)).deleteIndex(stringArgCaptor.capture());
Fixed, thanks.

2023-01-09 09:29 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +import org.hamcrest.CoreMatchers;
Fixed, thanks.

2023-01-09 09:29 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    Settings settings3 = mock(Settings.class);
Fixed, thanks.

2023-01-09 09:29 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    final String backupIndex3 = "backup_3";
Fixed, thanks.

2023-01-09 09:29 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    Settings settings3 = mock(Settings.class);
Fixed, thanks.

2023-01-09 09:29 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    String str3 = null;
Fixed, thanks.

2023-01-09 09:29 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    when(settings3.get("index.creation_date")).thenReturn(str3);
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    final String backupIndex1 = "backup_1";
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    final String backupIndex3 = "backup_3";
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    MappingMetadata mapping = mock(MappingMetadata.class);
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    verify(elasticsearchIndexHelperMock, times(0)).createIndex(anyString(), any());
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    verify(elasticsearchIndexHelperMock, times(0)).addAlias(anyString(), anyString());
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    AliasMetadata aliasMetadata1 = mock(AliasMetadata.class);
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    verify(elasticsearchIndexHelperMock, times(0)).addAlias(anyString(), anyString());
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    MappingMetadata mappingMock = mock(MappingMetadata.class);
Fixed, thanks.

2023-01-09 09:30 UTC, hihilary commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/sync/service/ElasticsearchIndexServiceTest.java
> +    MappingMetadata mappingMock = mock(MappingMetadata.class);
Fixed, thanks.

2023-01-09 10:29 UTC, JosephKelly approved these changes

2023-01-09 10:41 UTC, merged