fix: allow null DBC from revalidation services for disconnected doctors
Health-Education-England/tis-revalidation-integration pull request #403
Opened 2023-05-15 08:05 UTC by CaiWillis

TIS21-4510: Connections Discrepnacies Data Cleanup: Remove last- prefix from disconnected DBCs

2023-05-15 09:10 UTC, CaiWillis commented
Context
Our CDC (change data capture) service for reval captures changes in Reval and/or TIS in order to update Elasticsearch, which is what drives the connections and recommendations list pages.

We get one type of object from Reval, another from TIS, and both are mapped to a combined "MasterDoctorView" object when received by the CDC system.

Obviously, we get different data fields from each source (TIS and Reval), so we have NullValuePropertyMappingStrategy.IGNORE set on the mapper, which means we don't overwrite fields with null by default (e.g. TIS doesn't know about the GMC field doctorStatus, so we don't want the mapper setting that field to null every time we get an update from TIS)

As part of TIS21-4510, we want to be able to set designated body to null in order to show that a doctor has been disconnected, but currently null designated body changes are ignored.

Luckily we have separate CDC service classes for GMC changes and TIS changes, and also separate mapper overrides for updating an existing masterdoctorview! So I've gone with the easy solution of just sticking NullValuePropertyMappingStrategy.SET_TO_NULL on the methods used by the DoctorCDCService, so the TraineeUpdateCDCService will still ignore nulls! It looks to me like this will work out alright, but could use a sanity check

2023-05-15 14:37 UTC, JosephKelly requested changes

2023-05-15 14:37 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcDoctorServiceTest.java
> +    verify(mapper).updateMasterDoctorView(mapper.doctorToMasterView(newDoctor), existingDoctor);
This does look very flaky.  It is subject to the way equality is checked between objects.  You could use a captor and verify that it is the same "shape" as what we expect the `DoctorsForDB` object to be converted to.

Given that we've got a test covering `MasterDoctorViewMapper` and we are no longer using a `Mock<MasterDoctorViewMapper>`, this isn't necessary.  If we do want to verify the behaviour, we can use a captor for the "source" object.

2023-05-15 14:37 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcDoctorServiceTest.java
> +    assertThat(savedView.getTcsPersonId(), is(existingDoctor.getTcsPersonId()));
Nice!

2023-05-15 14:37 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcDoctorServiceTest.java
> +    verify(mapper).updateMasterDoctorView(mapper.doctorToMasterView(newDoctor), existingDoctor);
As above, I'd prefer this removed or verified with a captor.

2023-05-15 14:37 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/service/CdcDoctorServiceTest.java
> +        .getFullDocument();
Seems a bit odd to create an object in the test generator that you then unwrap.  I'm guessing it is done for consistency with what was there before, but this the only place the new method is called.
It would be great if you could "fix" (separate) the use of `.getCdcDoctorInsertCdcDocumentDto().getFullDocument()`.

2023-05-16 08:03 UTC, JosephKelly requested changes
There's unnecessary use of the `verify(mapper).updateMasterDoctorView` left and what looks like some line breaks added.

2023-05-16 08:03 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/testutil/CdcTestDataGenerator.java
> +
Please remove unless serving a purpose.

2023-05-16 08:12 UTC, JosephKelly commented on src/test/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/testutil/CdcTestDataGenerator.java
> +   * @return CdcDocumentDto CdcDoctor test instance
:facepalm: Just noticed the comment.  It looks like it hasn't been updated.

2023-05-16 08:29 UTC, JosephKelly approved these changes

2023-05-16 08:33 UTC, merged