feat:handle gmcNumber from reliable to unreliable
Health-Education-England/tis-revalidation-integration pull request #443
Opened 2023-10-02 00:17 UTC by hihilary

TIS21-5100

2023-10-03 23:43 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +      return MasterDoctorView.builder().id(viewToRemove.getId()).build();
I assume the doc id in `masterdoctorindex` should match the id in `recommendationindex`, and the updated entity we publish should have the id.

2023-10-04 08:35 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +    if (StringUtils.isEmpty(viewToRemove.getDesignatedBody())) {
This might be an issue if we end up needing a "disconnected" doctors tab for connections (we might not). Currently when we "hide (disconnect) all doctors" as part of the overnight sync job, we set designated body to null but keep the rest of the doctors info.

Maybe it's best to just remove this if condition and just remove TIS data and leave the record in place otherwise?

2023-10-04 09:09 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +    if (StringUtils.isEmpty(viewToRemove.getDesignatedBody())) {
Ah sorry I didn't spot that by this point, gmcReferenceNumber is already considered null - so actually this is legitimate because it's completely useless to have a doctor with no TIS ID or Gmc Reference number - so yeah delete it completely

2023-10-04 09:19 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +      removeTisInfoIfGmcNumberNotMatch(receivedDto);
should this be in another if statement?

2023-10-04 10:31 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +      removeTisInfoIfGmcNumberNotMatch(receivedDto);
In the method itself, it gets ES docs by tcsPersonId and GmcReferenceNumberNot, if no records found, it does nothing.

2023-10-04 10:32 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +    if (StringUtils.isEmpty(viewToRemove.getDesignatedBody())) {
The if condition and operation of deleting records are removed.

2023-10-04 13:41 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +            .save(mapper.updateMasterDoctorView(receivedDto, view));
Have you accounted for the ignore nulls default strategy?

2023-10-04 13:42 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +        publishUpdate(updatedView);
Are you confident the IDs will be the same?

2023-10-04 13:48 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +            .save(mapper.updateMasterDoctorView(receivedDto, view));
I didn't change the logic here. And I've checked the compiled `MasterDoctorViewMapperImpl` file. Null checks has been removed for all tcs related fields except for tcsPersonId, but we have checked tcsPersonId in the listener.
`@Override
    public MasterDoctorView updateMasterDoctorView(ConnectionInfoDto source, MasterDoctorView target) {
        if ( source == null ) {
            return null;
        }

        target.setProgrammeName( source.getProgrammeName() );
        target.setMembershipType( source.getProgrammeMembershipType() );
        target.setProgrammeOwner( source.getProgrammeOwner() );
        target.setCurriculumEndDate( source.getCurriculumEndDate() );
        target.setMembershipStartDate( source.getProgrammeMembershipStartDate() );
        target.setMembershipEndDate( source.getProgrammeMembershipEndDate() );
        target.setTcsDesignatedBody( source.getTcsDesignatedBody() );
        target.setPlacementGrade( source.getPlacementGrade() );
        if ( source.getTcsPersonId() != null ) {
            target.setTcsPersonId( source.getTcsPersonId() );
        }
        if ( source.getGmcReferenceNumber() != null ) {
            target.setGmcReferenceNumber( source.getGmcReferenceNumber() );
        }
        if ( source.getDoctorFirstName() != null ) {
            target.setDoctorFirstName( source.getDoctorFirstName() );
        }
        if ( source.getDoctorLastName() != null ) {
            target.setDoctorLastName( source.getDoctorLastName() );
        }
        if ( source.getSubmissionDate() != null ) {
            target.setSubmissionDate( source.getSubmissionDate() );
        }
        if ( source.getDesignatedBody() != null ) {
            target.setDesignatedBody( source.getDesignatedBody() );
        }

        return target;
    }`

2023-10-04 13:51 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +        publishUpdate(updatedView);
After full sync, the data in recommendationindex and masterdoctorindex are exactly the same. 
And I think all data changes in TIS or Reval DocumentDB should update masterdoctorindex first, and then by cdc, recommendationindex gets update. I could not think of a reason why they don't match.

2023-10-04 13:52 UTC, JosephKelly requested changes
TBH, I only got part way through considering suggestions of how to change this.  There are a few things I'd like you to look at if sticking with the approach.

I think I was contemplating the pseudocode for this because as implemented.  If we `detachTisInfoForFilteredOutRecords()`, then there are still lookups for records by GMC number (null) and TIS id (also none?).

2023-10-04 13:52 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcRabbitMessageListener.java
> +    }
N.B.  Without any specific configuration this will block the queue.  I don't think there is anything in the integration project that uses a dead letter queue.  Given the strong tie to the process in TCS, I think alerting and throwing an `AmqpRejectAndDontRequeueException` is sufficient.

2023-10-04 13:52 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +            viewsFromGmcNumber.isEmpty() ? Lists.newArrayList(new MasterDoctorView())
`List.of()` is preferred to `Lists.newArrayList()`.

2023-10-04 13:52 UTC, JosephKelly commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +
Almost certainly not going to happen but this introduces the potential for a discrepancy between the value of `this.repository` & `getRepositry()`.  I understand that repeated calls to `getRepository()` doesn't look as neat.  I'd want to look at the history and understand if/why super.repository shouldn't be `protected`.

2023-10-04 14:05 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +        publishUpdate(updatedView);
If a TIS person is created with a GMC ID that hasn't come through from GMC (don't know how likely that is) then maybe there'd be a problem? Or am I reading that wrong

2023-10-04 14:18 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcRabbitMessageListener.java
> +    }
I added this because I've seen some similar exception thrown in Recommendation service: https://github.com/Health-Education-England/tis-revalidation-recommendation/blob/d5599faab3fa6787468ac37417b7e7ec689e6e66/application/src/main/java/uk/nhs/hee/tis/revalidation/messages/RabbitMessageListener.java#L101.

2023-10-04 14:18 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/message/listener/CdcRabbitMessageListener.java
> +    }
Let me try this locally and fix it.

2023-10-04 14:19 UTC, hihilary commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +
Not sure why it's not protected.
That's a good point, let me revert this change back.

2023-10-04 14:21 UTC, CaiWillis commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/cdc/service/CdcTraineeUpdateService.java
> +        publishUpdate(updatedView);
Oh and actually even if it didnt go through to the recommendation index it wouldnt matter anyway because recommendations wouldnt care, cool

2023-10-04 14:22 UTC, hihilary commented
> TBH, I only got part way through considering suggestions of how to change this. There are a few things I'd like you to look at if sticking with the approach.
> 
> I think I was contemplating the pseudocode for this because as implemented. If we `detachTisInfoForFilteredOutRecords()`, then there are still lookups for records by GMC number (null) and TIS id (also none?).

I really thought about these. But I did some query on both indices and confirmed GMC number is not null.
I think here I only want to detach TIS info, and won't be bothered if TIS id is null.

2023-10-05 10:24 UTC, CaiWillis approved these changes
I'm confident enough that it will work and that the logic is sound, I'm not smart enough to know if it can be optimized further. Happy to approve assuming Pepe's changes are addressed

2023-10-05 10:41 UTC, JosephKelly approved these changes

2023-10-11 13:56 UTC, merged