feat: added the endpoint for pulling reval admin from profile
Health-Education-England/tis-revalidation-integration pull request #93
Opened 2020-10-20 13:11 UTC by jayanta2018

TISNEW-5602

2020-10-20 13:15 UTC, uzairbaig requested changes

2020-10-20 13:15 UTC, uzairbaig commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ProfileServiceRouter.java
> +  private static final String API_ASSIGN_REVAL_ADMINS = "/api/hee-users-with-roles/HEE Admin Revalidation, RVAdmin";
UI should pass these role names to backend. Otherwise there is no advantage of keep it as list. If we need to add a new role or remove an existing role we have to change the code.

2020-10-21 12:29 UTC, jayanta2018 commented on src/main/java/uk/nhs/hee/tis/revalidation/integration/router/service/ProfileServiceRouter.java
> +  private static final String API_ASSIGN_REVAL_ADMINS = "/api/hee-users-with-roles/HEE Admin Revalidation, RVAdmin";
Done as we discussed.

2020-10-21 12:31 UTC, uzairbaig approved these changes

2020-10-21 12:31 UTC, merged